---
- name: Configure webservers
  hosts: webservers
  tasks:
    - name: Install nginx
      apt: name=nginx
    - name: install config file
      template: src=nginx.conf.j2 dest=/etc/nginx/ngingx.onf
      notify: restart nginx
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
