- name: Mess with stdout
  hosts: all
  gather_facts: no
  tasks:
    - name: Getting output
      command: pwd
      register: command
    
    - name: Printing output
      debug:
        msg: "stdout: {{command.stdout}}"
